
package net.geant2.jra3.administration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:18 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://administration.jra3.geant2.net/", name = "getReservationResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://administration.jra3.geant2.net/", name = "getReservationResponse")

public class GetReservationResponse {

@XmlElement(namespace = "", name = "Reservation")
    private net.geant2.jra3.reservation.Reservation Reservation;

    public net.geant2.jra3.reservation.Reservation getReservation ()     {
	           return this.Reservation;
        }

    public void setReservation (   net.geant2.jra3.reservation.Reservation newReservation  )     {
	           this.Reservation = newReservation;
        }

}

