
package net.geant.autobahn.administration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:18 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://administration.autobahn.geant.net/", name = "getStatus")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://administration.autobahn.geant.net/", name = "getStatus")

public class GetStatus {


}

