
package net.geant.autobahn.dm2idm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 15 15:30:56 CET 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

public final class Dm2Idm_Dm2IdmPort_Client {

    private static final QName SERVICE_NAME = new QName("http://dm2idm.jra3.geant2.net/", "Dm2IdmService");

    private Dm2Idm_Dm2IdmPort_Client() {
    }

    public static void main(String args[]) throws Exception {

        if (args.length == 0) { 
            System.out.println("please specify wsdl");
            System.exit(1); 
        }
        URL wsdlURL = null;
        File wsdlFile = new File(args[0]);
        try {
            if (wsdlFile.exists()) {
                wsdlURL = wsdlFile.toURL();
            } else {
                wsdlURL = new URL(args[0]);
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
      
        Dm2IdmService ss = new Dm2IdmService(wsdlURL, SERVICE_NAME);
        Dm2Idm port = ss.getDm2IdmPort();  
        
        {
        System.out.println("Invoking activate...");
        java.lang.String _activate_resID = "";
        boolean _activate_success = false;
        port.activate(_activate_resID, _activate_success);


        }
        {
        System.out.println("Invoking finish...");
        java.lang.String _finish_resID = "";
        boolean _finish_success = false;
        port.finish(_finish_resID, _finish_success);


        }

        System.exit(0);
    }

}
