
package net.geant.autobahn.dm2idm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import net.geant.autobahn.dm2idm.Dm2Idm;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 15 15:30:57 CET 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "Dm2IdmService", targetNamespace = "http://dm2idm.jra3.geant2.net/", wsdlLocation = "file:wsdl/dm2idm.wsdl")
public class Dm2IdmService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://dm2idm.jra3.geant2.net/", "Dm2IdmService");
    private final static QName Dm2IdmPort = new QName("http://dm2idm.jra3.geant2.net/", "Dm2IdmPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/dm2idm.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/dm2idm.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Dm2IdmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Dm2IdmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dm2IdmService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Dm2IdmPort
     */
    @WebEndpoint(name = "Dm2IdmPort")
    public Dm2Idm getDm2IdmPort() {
        return (Dm2Idm)super.getPort(Dm2IdmPort, Dm2Idm.class);
    }

}
