
package net.geant2.jra3.useraccesspoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Mon Mar 02 13:20:42 CET 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "UserAccessPointException", targetNamespace = "http://useraccesspoint.jra3.geant2.net/")

public class UserAccessPointExceptionException extends Exception {
    public static final long serialVersionUID = 20090302132042L;
    
    private net.geant2.jra3.useraccesspoint.UserAccessPointException userAccessPointException;

    public UserAccessPointExceptionException() {
        super();
    }
    
    public UserAccessPointExceptionException(String message) {
        super(message);
    }
    
    public UserAccessPointExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public UserAccessPointExceptionException(String message, net.geant2.jra3.useraccesspoint.UserAccessPointException userAccessPointException) {
        super(message);
        this.userAccessPointException = userAccessPointException;
    }

    public UserAccessPointExceptionException(String message, net.geant2.jra3.useraccesspoint.UserAccessPointException userAccessPointException, Throwable cause) {
        super(message, cause);
        this.userAccessPointException = userAccessPointException;
    }

    public net.geant2.jra3.useraccesspoint.UserAccessPointException getFaultInfo() {
        return this.userAccessPointException;
    }
}
