
package net.geant2.jra3.useraccesspoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;
import net.geant2.jra3.useraccesspoint.UserAccessPoint;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Jul 01 12:46:44 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "UserAccessPointService", targetNamespace = "http://useraccesspoint.jra3.geant2.net/", wsdlLocation = "file:wsdl/useraccesspoint.wsdl")
public class UserAccessPointService{
	
	
	public final static QName SERVICE = new QName("http://useraccesspoint.jra3.geant2.net/", "UserAccessPointService");
    public final static QName UserAccessPointPort = new QName("http://useraccesspoint.jra3.geant2.net/", "UserAccessPointPort");    private Service service;
    
    public UserAccessPointService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(UserAccessPointPort, SOAPBinding.SOAP12HTTP_BINDING, endPoint);
    }
    
    /**
     * 
     * @return
     *     returns Idm2DmPort
     */
    @WebEndpoint(name = "AdministrationPort")
    public UserAccessPoint getUserAccessPointPort() {
        return service.getPort(UserAccessPoint.class);
    }
    
   
}
