
package net.es.oscars.oscars;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:32:27 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebFault(name = "BSSFault", targetNamespace = "http://oscars.es.net/OSCARS")

public class BSSFaultMessage extends Exception {
    public static final long serialVersionUID = 20100212153227L;
    
    private net.es.oscars.oscars.BSSFault bssFault;

    public BSSFaultMessage() {
        super();
    }
    
    public BSSFaultMessage(String message) {
        super(message);
    }
    
    public BSSFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public BSSFaultMessage(String message, net.es.oscars.oscars.BSSFault bssFault) {
        super(message);
        this.bssFault = bssFault;
    }

    public BSSFaultMessage(String message, net.es.oscars.oscars.BSSFault bssFault, Throwable cause) {
        super(message, cause);
        this.bssFault = bssFault;
    }

    public net.es.oscars.oscars.BSSFault getFaultInfo() {
        return this.bssFault;
    }
}
