
package net.es.oscars.oscars;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebFault(name = "InvalidTopicExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")

public class InvalidTopicExpressionFault extends Exception {
    public static final long serialVersionUID = 20100212154406L;
    
    private org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType invalidTopicExpressionFault;

    public InvalidTopicExpressionFault() {
        super();
    }
    
    public InvalidTopicExpressionFault(String message) {
        super(message);
    }
    
    public InvalidTopicExpressionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTopicExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType invalidTopicExpressionFault) {
        super(message);
        this.invalidTopicExpressionFault = invalidTopicExpressionFault;
    }

    public InvalidTopicExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType invalidTopicExpressionFault, Throwable cause) {
        super(message, cause);
        this.invalidTopicExpressionFault = invalidTopicExpressionFault;
    }

    public org.oasis_open.docs.wsn.b_2.InvalidTopicExpressionFaultType getFaultInfo() {
        return this.invalidTopicExpressionFault;
    }
}
