
package net.es.oscars.oscars;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebFault(name = "InvalidMessageContentExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")

public class InvalidMessageContentExpressionFault extends Exception {
    public static final long serialVersionUID = 20100212154406L;
    
    private org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault;

    public InvalidMessageContentExpressionFault() {
        super();
    }
    
    public InvalidMessageContentExpressionFault(String message) {
        super(message);
    }
    
    public InvalidMessageContentExpressionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageContentExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault) {
        super(message);
        this.invalidMessageContentExpressionFault = invalidMessageContentExpressionFault;
    }

    public InvalidMessageContentExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault, Throwable cause) {
        super(message, cause);
        this.invalidMessageContentExpressionFault = invalidMessageContentExpressionFault;
    }

    public org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType getFaultInfo() {
        return this.invalidMessageContentExpressionFault;
    }
}
