
package net.es.oscars.oscars;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import net.es.oscars.oscars.OSCARSNotify;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "OSCARSNotify", targetNamespace = "http://oscars.es.net/OSCARS", wsdlLocation = "file:OSCARS-Notify.wsdl")
public class OSCARSNotify_Service extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://oscars.es.net/OSCARS", "OSCARSNotify");
    private final static QName OSCARSNotify = new QName("http://oscars.es.net/OSCARS", "OSCARSNotify");
    static {
        URL url = null;
        try {
            url = new URL("file:OSCARS-Notify.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:OSCARS-Notify.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OSCARSNotify_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OSCARSNotify_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OSCARSNotify_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns OSCARSNotify
     */
    @WebEndpoint(name = "OSCARSNotify")
    public OSCARSNotify getOSCARSNotify() {
        return (OSCARSNotify)super.getPort(OSCARSNotify, OSCARSNotify.class);
    }

}
