
package net.es.oscars.oscars;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

import net.es.oscars.oscars.OSCARS;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:32:27 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "OSCARS", targetNamespace = "http://oscars.es.net/OSCARS", wsdlLocation = "http://150.140.8.11:80/oscars/OSCARS.wsdl")
public class OSCARS_Service extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://oscars.es.net/OSCARS", "OSCARS");
    private final static QName OSCARS = new QName("http://oscars.es.net/OSCARS", "OSCARS");
    static {
        URL url = null;
        try {
            url = new URL("wsdl/OSCARS.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/WEB-INF/classes/wsdl/OSCARS.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OSCARS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OSCARS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

/*    public OSCARS_Service(String endPoint) {
        service = Service.create(SERVICE);
        service.addPort(ProxyPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }*/

    public OSCARS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns OSCARS
     */
    @WebEndpoint(name = "OSCARS")
    public OSCARS getOSCARS() {
        return (OSCARS)super.getPort(OSCARS, OSCARS.class);
    }

}
