
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.es.oscars.oscars;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebResult;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@javax.jws.WebService(name = "OSCARSNotify", serviceName = "OSCARSNotify",
                      portName = "OSCARSNotify",
                      targetNamespace = "http://oscars.es.net/OSCARS", 
                      wsdlLocation = "file:OSCARS-Notify.wsdl" ,
		      endpointInterface = "net.es.oscars.oscars.OSCARSNotify")
                      
public class OSCARSNotifyImpl implements OSCARSNotify {

    private static final Logger LOG = Logger.getLogger(OSCARSNotifyImpl.class.getName());

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#subscribe(org.oasis_open.docs.wsn.b_2.Subscribe  subscribeRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.SubscribeResponse subscribe(org.oasis_open.docs.wsn.b_2.Subscribe subscribeRequest) throws InvalidMessageContentExpressionFault , UnsupportedPolicyRequestFault , InvalidProducerPropertiesExpressionFault , UnacceptableInitialTerminationTimeFault , UnrecognizedPolicyRequestFault , ResourceUnknownFault , TopicNotSupportedFault , NotifyMessageNotSupportedFault , InvalidFilterFault , TopicExpressionDialectUnknownFault , AAAFaultMessage , InvalidTopicExpressionFault , SubscribeCreationFailedFault    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#Subscribe");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#resumeSubscription(org.oasis_open.docs.wsn.b_2.ResumeSubscription  resumeSubscriptionRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.ResumeSubscriptionResponse resumeSubscription(org.oasis_open.docs.wsn.b_2.ResumeSubscription resumeSubscriptionRequest) throws ResourceUnknownFault , ResumeFailedFault , AAAFaultMessage    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#ResumeSubscription");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#registerPublisher(org.oasis_open.docs.wsn.br_2.RegisterPublisher  registerPublisherRequest )*
     */
    public org.oasis_open.docs.wsn.br_2.RegisterPublisherResponse registerPublisher(org.oasis_open.docs.wsn.br_2.RegisterPublisher registerPublisherRequest) throws PublisherRegistrationRejectedFault , UnacceptableInitialTerminationTimeFault , ResourceUnknownFault , PublisherRegistrationFailedFault , TopicNotSupportedFault , InvalidTopicExpressionFault    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#RegisterPublisher");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#unsubscribe(org.oasis_open.docs.wsn.b_2.Unsubscribe  unsubscribeRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.UnsubscribeResponse unsubscribe(org.oasis_open.docs.wsn.b_2.Unsubscribe unsubscribeRequest) throws UnableToDestroySubscriptionFault , ResourceUnknownFault , AAAFaultMessage    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#Unsubscribe");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#pauseSubscription(org.oasis_open.docs.wsn.b_2.PauseSubscription  pauseSubscriptionRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.PauseSubscriptionResponse pauseSubscription(org.oasis_open.docs.wsn.b_2.PauseSubscription pauseSubscriptionRequest) throws PauseFailedFault , ResourceUnknownFault , AAAFaultMessage    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#PauseSubscription");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#renew(org.oasis_open.docs.wsn.b_2.Renew  renewRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.RenewResponse renew(org.oasis_open.docs.wsn.b_2.Renew renewRequest) throws ResourceUnknownFault , UnacceptableTerminationTimeFault , AAAFaultMessage    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#Renew");
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#notify(org.oasis_open.docs.wsn.b_2.Notify  notify )*
     */
    public void notify(org.oasis_open.docs.wsn.b_2.Notify notify) { 
        //TODO : fill this with the necessary business logic
        
    }

    /* (non-Javadoc)
     * @see net.es.oscars.oscars.OSCARSNotify#destroyRegistration(org.oasis_open.docs.wsn.br_2.DestroyRegistration  destroyRegistrationRequest )*
     */
    public org.oasis_open.docs.wsn.br_2.DestroyRegistrationResponse destroyRegistration(org.oasis_open.docs.wsn.br_2.DestroyRegistration destroyRegistrationRequest) throws ResourceUnknownFault , ResourceNotDestroyedFault , AAAFaultMessage    { 
        //TODO : fill this with the necessary business logic
        throw new  java.lang.UnsupportedOperationException("Please implement " + this.getClass().getName() + "#DestroyRegistration");
    }

}
