
package net.es.oscars.oscars;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:32:27 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */
 
public class OSCARS_OSCARS_Server{

    protected OSCARS_OSCARS_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new OSCARSImpl();
        String address = "https://oscars-dev.es.net:9090/axis2/services/OSCARS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new OSCARS_OSCARS_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exitting");
        System.exit(0);
    }
}
