
package net.es.oscars.oscars;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */
 
public class OSCARSNotify_OSCARSNotify_Server{

    protected OSCARSNotify_OSCARSNotify_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new OSCARSNotifyImpl();
        String address = "https://oscars-dev.es.net:9090/axis2/services/OSCARSNotify";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new OSCARSNotify_OSCARSNotify_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exitting");
        System.exit(0);
    }
}
