
package net.es.oscars.oscars;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebFault(name = "PauseFailedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")

public class PauseFailedFault extends Exception {
    public static final long serialVersionUID = 20100212154406L;
    
    private org.oasis_open.docs.wsn.b_2.PauseFailedFaultType pauseFailedFault;

    public PauseFailedFault() {
        super();
    }
    
    public PauseFailedFault(String message) {
        super(message);
    }
    
    public PauseFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PauseFailedFault(String message, org.oasis_open.docs.wsn.b_2.PauseFailedFaultType pauseFailedFault) {
        super(message);
        this.pauseFailedFault = pauseFailedFault;
    }

    public PauseFailedFault(String message, org.oasis_open.docs.wsn.b_2.PauseFailedFaultType pauseFailedFault, Throwable cause) {
        super(message, cause);
        this.pauseFailedFault = pauseFailedFault;
    }

    public org.oasis_open.docs.wsn.b_2.PauseFailedFaultType getFaultInfo() {
        return this.pauseFailedFault;
    }
}
