
package net.es.oscars.oscars;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 12 15:44:06 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebFault(name = "ResourceNotDestroyedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")

public class ResourceNotDestroyedFault extends Exception {
    public static final long serialVersionUID = 20100212154406L;
    
    private org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault;

    public ResourceNotDestroyedFault() {
        super();
    }
    
    public ResourceNotDestroyedFault(String message) {
        super(message);
    }
    
    public ResourceNotDestroyedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault) {
        super(message);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault, Throwable cause) {
        super(message, cause);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType getFaultInfo() {
        return this.resourceNotDestroyedFault;
    }
}
