
package net.geant.autobahn.gui.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:27 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://gui.autobahn.geant.net/", name = "reservationChanged")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://gui.autobahn.geant.net/", name = "reservationChanged")

public class ReservationChanged {

@XmlElement(namespace = "", name = "idm")
    private java.lang.String idm;
@XmlElement(namespace = "", name = "serviceId")
    private java.lang.String serviceId;
@XmlElement(namespace = "", name = "resID")
    private java.lang.String resID;
@XmlElement(namespace = "", name = "state")
    private net.geant.autobahn.gui.ReservationChangedType state;
@XmlElement(namespace = "", name = "message")
    private java.lang.String message;

    public java.lang.String getIdm ()     {
	           return this.idm;
        }

    public void setIdm (   java.lang.String newIdm  )     {
	           this.idm = newIdm;
        }

    public java.lang.String getServiceId ()     {
	           return this.serviceId;
        }

    public void setServiceId (   java.lang.String newServiceId  )     {
	           this.serviceId = newServiceId;
        }

    public java.lang.String getResID ()     {
	           return this.resID;
        }

    public void setResID (   java.lang.String newResID  )     {
	           this.resID = newResID;
        }

    public net.geant.autobahn.gui.ReservationChangedType getState ()     {
	           return this.state;
        }

    public void setState (   net.geant.autobahn.gui.ReservationChangedType newState  )     {
	           this.state = newState;
        }

    public java.lang.String getMessage ()     {
	           return this.message;
        }

    public void setMessage (   java.lang.String newMessage  )     {
	           this.message = newMessage;
        }

}

