
package net.geant.autobahn.gui.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:27 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://gui.autobahn.geant.net/", name = "reservationChangedResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://gui.autobahn.geant.net/", name = "reservationChangedResponse")

public class ReservationChangedResponse {


}

