
package net.geant.autobahn.administration;

import java.io.FileNotFoundException;
import java.io.IOException;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;
import javax.xml.xpath.XPathException;

import org.apache.log4j.Logger;

import net.geant.autobahn.administration.Administration;
import net.geant.autobahn.edugain.WSSecurity;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Apr 25 14:21:46 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "AdministrationService", targetNamespace = "http://administration.autobahn.geant.net/", wsdlLocation = "file:wsdl/administration.wsdl")
public class AdministrationService {

	private final static QName SERVICE = new QName("http://administration.autobahn.geant.net/", "AdministrationService");
    private final static QName AdministrationPort = new QName("http://administration.autobahn.geant.net/", "AdministrationPort");
    private Service service;
    private final static Logger log = Logger.getLogger(AdministrationService.class);
    
    public AdministrationService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(AdministrationPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }
    
    /**
     * 
     * @return
     *     returns AdministrationPort
     */
    @WebEndpoint(name = "AdministrationPort")
    public Administration getAdministrationPort() {
        
    	Administration port = service.getPort(Administration.class);
    	
    	WSSecurity administration = null;
    	
        try {
            administration = new WSSecurity("../etc/security");
        } catch (XPathException e) {
            log.error("Couldn't create security object: " + e.getMessage());
        }   
        
        administration.setClientTimeout(port);
        
        try {
            administration.configureEndpoint(port);
        } catch (FileNotFoundException e) {
            log.error("File not found: " + e.getMessage());
        } catch (IOException e) {
            log.error("I/O exception : " + e.getMessage());
        } catch (Exception e) {
            log.error("General exception: " + e.getMessage());
        } catch (Throwable e) {
            log.error("Exception: " + e.getMessage());
        }
		return port;
    }

}
