
/*
 * 
 */

package net.geant.autobahn.amanager;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Sep 03 16:44:02 CEST 2009
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "AutobahnManagerService", 
                  wsdlLocation = "file:wsdl/manager.wsdl",
                  targetNamespace = "http://amanager.jra3.geant2.net/") 
public class AutobahnManagerService {

	private Service service;
	
    public final static QName SERVICE = new QName("http://amanager.jra3.geant2.net/", "AutobahnManagerService");
    public final static QName AutobahnManagerPort = new QName("http://amanager.jra3.geant2.net/", "AutobahnManagerPort");


    public AutobahnManagerService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(AutobahnManagerPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }

    /**
     * 
     * @return
     *     returns AutobahnManager
     */
    @WebEndpoint(name = "AutobahnManagerPort")
    public AutobahnManager getAutobahnManagerPort() {
    	return service.getPort(AutobahnManagerPort, AutobahnManager.class);
    }
}
