
package net.geant.autobahn.amanager;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 08 13:58:19 CEST 2009
 * Generated source version: 2.2.2
 * 
 */

public final class AutobahnManager_AutobahnManagerPort_Client {

    private AutobahnManager_AutobahnManagerPort_Client() {
    }

    public static void main(String args[]) throws Exception {

    	AutobahnManager client = new AutobahnManagerService(
				"http://localhost:8080/autobahn/manager").getAutobahnManagerPort();
    	
    	client.halt();
    }

}
