package net.geant.autobahn.amanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 08 13:58:19 CEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://amanager.jra3.geant2.net/", name = "AutobahnManager")
@XmlSeeAlso({ObjectFactory.class})
public interface AutobahnManager {

    @ResponseWrapper(localName = "getServicesResponse", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.GetServicesResponse")
    @RequestWrapper(localName = "getServices", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.GetServices")
    @WebResult(name = "services", targetNamespace = "")
    @WebMethod
    public java.util.List<java.lang.String> getServices();

    @ResponseWrapper(localName = "unregisterServiceResponse", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.UnregisterServiceResponse")
    @RequestWrapper(localName = "unregisterService", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.UnregisterService")
    @WebMethod
    public void unregisterService(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @ResponseWrapper(localName = "haltResponse", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.HaltResponse")
    @RequestWrapper(localName = "halt", targetNamespace = "http://amanager.jra3.geant2.net/", className = "net.geant2.jra3.amanager.Halt")
    @WebMethod
    public void halt();
}
