
package net.geant.autobahn.tool;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 22 14:54:58 CET 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "ToolService", targetNamespace = "http://tool.autobahn.geant.net/", wsdlLocation = "file:wsdl/tool.wsdl")
public class ToolService {

    private final static QName SERVICE = new QName("http://tool.autobahn.geant.net/", "ToolService");
    private final static QName ToolPort = new QName("http://tool.autobahn.geant.net/", "ToolPort");
    private Service service;
    
    public ToolService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(ToolPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }

    /**
     * 
     * @return
     *     returns ToolPort
     */
    @WebEndpoint(name = "ToolPort")
    public Tool getToolPort() {
        return service.getPort(ToolPort, Tool.class);
    }

}
