
package net.geant.autobahn.interdomain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import net.geant.autobahn.interdomain.Interdomain;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 15 15:30:45 CET 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "InterdomainService", targetNamespace = "http://interdomain.jra3.geant2.net/", wsdlLocation = "file:wsdl/interdomain.wsdl")
public class InterdomainService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://interdomain.jra3.geant2.net/", "InterdomainService");
    private final static QName InterdomainPort = new QName("http://interdomain.jra3.geant2.net/", "InterdomainPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/interdomain.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/interdomain.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InterdomainService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterdomainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterdomainService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns InterdomainPort
     */
    @WebEndpoint(name = "InterdomainPort")
    public Interdomain getInterdomainPort() {
        return (Interdomain)super.getPort(InterdomainPort, Interdomain.class);
    }

}
