<option value="+10:30">Australian Central Daylight Time</option>
<option value="+09:30">Australian Central Standard Time</option>
<option value="-03:00">Atlantic Daylight Time</option>
<option value="+11:00">Australian Eastern Daylight Time or Australian Eastern Summer Time</option>
<option value="+10:00">Australian Eastern Standard Time</option>
<option value="-08:00">Alaska Daylight Time</option>
<option value="-09:00">Alaska Standard Time</option>
<option value="-04:00">Atlantic Standard Time</option>
<option value="+09:00">Australian Western Daylight Time</option>
<option value="+08:00">Australian Western Standard Time</option>
<option value="+02:00">Bravo Time Zone</option>
<option value="+01:00">British Summer Time</option>
<option value="+03:00">Charlie Time Zone</option>
<option value="+10:30">Central Daylight Time(Australia)</option>
<option value="-05:00">Central Daylight Time(North America)</option>
<option value="+02:00">Central European Daylight Time</option>
<option value="+02:00">Central European Summer Time</option>
<option value="+01:00">Central European Time</option>
<option value="+10:30">Central Summer Time(Australia)</option>
<option value="+09:30">Central Standard Time(Australia)</option>
<option value="-06:00">Central Standard Time(North America)</option>
<option value="+07:00">Christmas Island Time(Australia)</option>
<option value="+04:00">Delta Time Zone</option>
<option value="+05:00">Echo Time Zone</option>
<option value="+11:00">Eastern Daylight Time(Australia)</option>
<option value="-04:00">Eastern Daylight Time(North America)</option>
<option value="+03:00">Eastern European Daylight Time</option>
<option value="+03:00">Eastern European Summer Time</option>
<option value="+02:00">Eastern European Time</option>
<option value="+11:00">Eastern Summer Time(Australia)</option>
<option value="+10:00">Eastern Standard Time(Australia)</option>
<option value="-05:00">Eastern Standard Time(North America)</option>
<option value="+06:00">Foxtrot Time Zone</option>
<option value="+07:00">Golf Time Zone</option>
<option value="+00:00">Greenwich Mean Time(GMT-UTC)</option>
<option value="+08:00">Hotel Time Zone</option>
<option value="-03:00">Heure Avancée de l'Atlantique</option>
<option value="-05:00">Heure Avancée du Centre</option>
<option value="-09:00">Hawaii-Aleutian Daylight Time</option>
<option value="-04:00">Heure Avancée de l'Est	North</option>
<option value="-07:00">Heure Avancée du Pacifique</option>
<option value="-06:00">Heure Avancée des Rocheuses</option>
<option value="-10:00">Hawaii-Aleutian Standard Time</option>
<option value="-02:30">Heure Avancée de Terre-Neuve</option>
<option value="-08:00">Heure Avancée du Yukon</option>
<option value="-04:00">Heure Normale de l'Atlantique</option>
<option value="-06:00">Heure Normale du Centre</option>
<option value="-05:00">Heure Normale de l'Est</option>
<option value="-08:00">Heure Normale du Pacifique</option>
<option value="-07:00">Heure Normale des Rocheuses</option>
<option value="-03:30">Heure Normale de Terre-Neuve</option>
<option value="-09:00">Heure Normale du Yukon</option>
<option value="+09:00">India Time Zone</option>
<option value="+01:00">Irish Summer Time</option>
<option value="+10:00">Kilo Time Zone</option>
<option value="+11:00">Lima Time Zone</option>
<option value="+12:00">Mike Time Zone</option>
<option value="-06:00">Mountain Daylight Time(North America)</option>
<option value="+02:00">Mitteleuroäische Sommerzeit</option>
<option value="+01:00">Mitteleuropäische Zeit</option>
<option value="-07:00">Mountain Standard Time(North America)</option>
<option value="-01:00">November Time Zone</option>
<option value="-02:30">Newfoundland Daylight Time</option>
<option value="+11:30">Norfolk (Island) Time</option>
<option value="-03:30">Newfoundland Standard Time</option>
<option value="-02:00">Oscar Time Zone</option>
<option value="-03:00">Papa Time Zone</option>
<option value="-07:00">Pacific Daylight Time</option>
<option value="-08:00">Pacific Standard Time</option>
<option value="-04:00">Quebec Time Zone</option>
<option value="-05:00">Romeo Time Zone</option>
<option value="-06:00">Sierra Time Zone</option>
<option value="-07:00">Tango Time Zone</option>
<option value="-08:00">Uniform Time Zone</option>
<option value="+00:00" selected="true">(UTC)Coordinated Universal Time</option>
<option value="-09:00">Victor Time Zone</option>
<option value="-10:00">Whiskey Time Zone</option>
<option value="+09:00">Western Daylight Time</option>
<option value="+01:00">Western European Daylight Time	Europe</option>
<option value="+01:00">Western European Summer Time</option>
<option value="+00:00">Western European Time</option>
<option value="+09:00">Western Summer Time</option>
<option value="+08:00">Western Standard Time</option>
<option value="-11:00">X-ray Time Zone</option>
<option value="-12:00">Yankee Time Zone</option>
<option value="+00:00">Zulu Time Zone</option>