
/*
 * 
 */

package net.geant2.cnis.autobahn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 08 14:53:37 EEST 2009
 * Generated source version: 2.2.2
 * 
 */


@WebServiceClient(name = "Autobahn", 
                  wsdlLocation = "file:wsdl/cnis.wsdl",
                  targetNamespace = "http://autobahn.cnis.geant2.net") 
public class Autobahn extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://autobahn.cnis.geant2.net", "Autobahn");
    public final static QName AutobahnHttpPort = new QName("http://autobahn.cnis.geant2.net", "AutobahnHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/cnis.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/cnis.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Autobahn(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Autobahn(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Autobahn() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AutobahnPortType
     */
    @WebEndpoint(name = "AutobahnHttpPort")
    public AutobahnPortType getAutobahnHttpPort() {
        return super.getPort(AutobahnHttpPort, AutobahnPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutobahnPortType
     */
    @WebEndpoint(name = "AutobahnHttpPort")
    public AutobahnPortType getAutobahnHttpPort(WebServiceFeature... features) {
        return super.getPort(AutobahnHttpPort, AutobahnPortType.class, features);
    }

}
