
package net.geant2.cnis.autobahn;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 08 14:53:37 EEST 2009
 * Generated source version: 2.2.2
 * 
 */

public final class AutobahnPortType_AutobahnHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://autobahn.cnis.geant2.net", "Autobahn");

    private AutobahnPortType_AutobahnHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Autobahn.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Autobahn ss = new Autobahn(wsdlURL, SERVICE_NAME);
        AutobahnPortType port = ss.getAutobahnHttpPort();  
        
        {
        System.out.println("Invoking getTopology...");
        net.geant2.cnis.autobahn.xml.AutobahnToCnisRequest _getTopology_request = null;
        net.geant2.cnis.autobahn.xml.CnisToAutobahnResponse _getTopology__return = port.getTopology(_getTopology_request);
        System.out.println("getTopology.result=" + _getTopology__return);


        }

        System.exit(0);
    }

}
