package net.geant2.cnis.autobahn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.2
 * Thu Oct 08 14:53:37 EEST 2009
 * Generated source version: 2.2.2
 * 
 */
 
@WebService(targetNamespace = "http://autobahn.cnis.geant2.net", name = "AutobahnPortType")
@XmlSeeAlso({net.geant2.cnis.autobahn.xml.ObjectFactory.class,net.geant2.cnis.autobahn.xml.ethernet.ObjectFactory.class,net.geant2.cnis.autobahn.xml.sdh.ObjectFactory.class,net.geant2.cnis.autobahn.xml.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AutobahnPortType {

    @WebResult(name = "response", targetNamespace = "http://cnis.geant2.net/autobahn/xml", partName = "response")
    @WebMethod
    public net.geant2.cnis.autobahn.xml.CnisToAutobahnResponse getTopology(
        @WebParam(partName = "request", name = "request", targetNamespace = "http://cnis.geant2.net/autobahn/xml")
        net.geant2.cnis.autobahn.xml.AutobahnToCnisRequest request
    );
}
