
package net.geant.autobahn.useraccesspoint;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;
import javax.xml.xpath.XPathException;

import org.apache.log4j.Logger;

import net.geant.autobahn.useraccesspoint.UserAccessPoint;
import net.geant.autobahn.edugain.WSSecurity;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Jul 01 12:46:44 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "UserAccessPointService", targetNamespace = "http://useraccesspoint.autobahn.geant.net/", wsdlLocation = "file:wsdl/useraccesspoint.wsdl")
public class UserAccessPointService{
	
	
	public final static QName SERVICE = new QName("http://useraccesspoint.autobahn.geant.net/", "UserAccessPointService");
    public final static QName UserAccessPointPort = new QName("http://useraccesspoint.autobahn.geant.net/", "UserAccessPointPort");    
    private Service service;
    private final static Logger log = Logger.getLogger(UserAccessPointService.class);
    
    
    public UserAccessPointService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(UserAccessPointPort, SOAPBinding.SOAP12HTTP_BINDING, endPoint);
    }
    
    /**
     * 
     * @return
     *     returns UserAccessPointPort
     */
    @WebEndpoint(name = "UserAccessPointPort")
    public UserAccessPoint getUserAccessPointPort() {
    	UserAccessPoint port = service.getPort(UserAccessPoint.class);
    	
    	WSSecurity userAccessPoint = null;
        
    	try {
    	    userAccessPoint = new WSSecurity("../etc/edugain");
        } catch (XPathException e) {
            log.error("Couldn't create security object: " + e.getMessage());
        }   
        
        userAccessPoint.setClientTimeout(port);
        
        try {
            userAccessPoint.configureEndpoint(port);
        } catch (FileNotFoundException e) {
            log.error("File not found: " + e.getMessage());
        } catch (IOException e) {
            log.error("I/O exception : " + e.getMessage());
        } catch (Exception e) {
            log.error("General exception: " + e.getMessage());
        } catch (Throwable e) {
            log.error("Exception: " + e.getMessage());
        }
		
		return port;
    }
    
   
}
