
package net.geant.autobahn.useraccesspoint;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

import net.geant.autobahn.useraccesspoint.UserAccessPoint;
import net.geant.edugain.WSSecurity;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Jul 01 12:46:44 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "UserAccessPointService", targetNamespace = "http://useraccesspoint.autobahn.geant.net/", wsdlLocation = "file:wsdl/useraccesspoint.wsdl")
public class UserAccessPointService{
	
	
	public final static QName SERVICE = new QName("http://useraccesspoint.autobahn.geant.net/", "UserAccessPointService");
    public final static QName UserAccessPointPort = new QName("http://useraccesspoint.autobahn.geant.net/", "UserAccessPointPort");    private Service service;
    
    public UserAccessPointService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(UserAccessPointPort, SOAPBinding.SOAP12HTTP_BINDING, endPoint);
    }
    
    /**
     * 
     * @return
     *     returns Idm2DmPort
     */
    @WebEndpoint(name = "AdministrationPort")
    public UserAccessPoint getUserAccessPointPort() {
        
    	UserAccessPoint port = service.getPort(UserAccessPoint.class);
    	
    	WSSecurity.setClientTimeout(port);
    	
		try {
			WSSecurity.configureEndpoint(port);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Throwable e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return port;
    }
    
   
}
