
package net.geant.autobahn.useraccesspoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Mon Mar 02 15:39:33 CET 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "UserAccessPointException", targetNamespace = "http://useraccesspoint.autobahn.geant.net/")

public class UserAccessPointException_Exception extends Exception {
    public static final long serialVersionUID = 20090302153933L;
    
    private net.geant.autobahn.useraccesspoint.UserAccessPointException userAccessPointException;

    public UserAccessPointException_Exception() {
        super();
    }
    
    public UserAccessPointException_Exception(String message) {
        super(message);
    }
    
    public UserAccessPointException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserAccessPointException_Exception(String message, net.geant.autobahn.useraccesspoint.UserAccessPointException userAccessPointException) {
        super(message);
        this.userAccessPointException = userAccessPointException;
    }

    public UserAccessPointException_Exception(String message, net.geant.autobahn.useraccesspoint.UserAccessPointException userAccessPointException, Throwable cause) {
        super(message, cause);
        this.userAccessPointException = userAccessPointException;
    }

    public net.geant.autobahn.useraccesspoint.UserAccessPointException getFaultInfo() {
        return this.userAccessPointException;
    }
}
