
package net.geant.autobahn.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Jun 18 15:05:42 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "AAIException", targetNamespace = "http://tool.autobahn.geant.net/")
public class AAIException_Exception extends Exception {
    public static final long serialVersionUID = 20100618150542L;
    
    private net.geant.autobahn.tool.AAIException aaiException;

    public AAIException_Exception() {
        super();
    }
    
    public AAIException_Exception(String message) {
        super(message);
    }
    
    public AAIException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AAIException_Exception(String message, net.geant.autobahn.tool.AAIException aaiException) {
        super(message);
        this.aaiException = aaiException;
    }

    public AAIException_Exception(String message, net.geant.autobahn.tool.AAIException aaiException, Throwable cause) {
        super(message, cause);
        this.aaiException = aaiException;
    }

    public net.geant.autobahn.tool.AAIException getFaultInfo() {
        return this.aaiException;
    }
}
