
package net.geant.autobahn.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Jun 18 15:05:42 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "ResourceNotFoundException", targetNamespace = "http://tool.autobahn.geant.net/")
public class ResourceNotFoundException_Exception extends Exception {
    public static final long serialVersionUID = 20100618150542L;
    
    private net.geant.autobahn.tool.ResourceNotFoundException resourceNotFoundException;

    public ResourceNotFoundException_Exception() {
        super();
    }
    
    public ResourceNotFoundException_Exception(String message) {
        super(message);
    }
    
    public ResourceNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotFoundException_Exception(String message, net.geant.autobahn.tool.ResourceNotFoundException resourceNotFoundException) {
        super(message);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public ResourceNotFoundException_Exception(String message, net.geant.autobahn.tool.ResourceNotFoundException resourceNotFoundException, Throwable cause) {
        super(message, cause);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public net.geant.autobahn.tool.ResourceNotFoundException getFaultInfo() {
        return this.resourceNotFoundException;
    }
}
