
package net.geant.autobahn.tool;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Jun 18 15:05:42 CEST 2010
 * Generated source version: 2.2.5
 * 
 */
 
public class Tool_ToolPort_Server{

    protected Tool_ToolPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ToolImpl();
        String address = "http://localhost:9090/ToolPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Tool_ToolPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
