
package net.geant2.jra3.dm2idm.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 04 12:14:07 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://dm2idm.jra3.geant2.net/", name = "activate")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://dm2idm.jra3.geant2.net/", name = "activate")

public class Activate {

@XmlElement(namespace = "", name = "resID")
    private java.lang.String resID;
@XmlElement(namespace = "", name = "success")
    private boolean success;

    public java.lang.String getResID ()     {
	           return this.resID;
        }

    public void setResID (   java.lang.String newResID  )     {
	           this.resID = newResID;
        }

    public boolean getSuccess ()     {
	           return this.success;
        }

    public void setSuccess (   boolean newSuccess  )     {
	           this.success = newSuccess;
        }

}

