
package net.geant.autobahn.idm2dm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import net.geant.autobahn.idm2dm.Idm2Dm;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Feb 15 15:30:52 CET 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "Idm2DmService", targetNamespace = "http://idm2dm.autobahn.geant.net/", wsdlLocation = "file:wsdl/idm2dm.wsdl")
public class Idm2DmService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://idm2dm.autobahn.geant.net/", "Idm2DmService");
    private final static QName Idm2DmPort = new QName("http://idm2dm.autobahn.geant.net/", "Idm2DmPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/idm2dm.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/idm2dm.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Idm2DmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Idm2DmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Idm2DmService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Idm2DmPort
     */
    @WebEndpoint(name = "Idm2DmPort")
    public Idm2Dm getIdm2DmPort() {
        return (Idm2Dm)super.getPort(Idm2DmPort, Idm2Dm.class);
    }

}
