
package net.geant.autobahn.tool;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Jun 18 15:05:41 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

public final class Tool_ToolPort_Client {

    private static final QName SERVICE_NAME = new QName("http://tool.autobahn.geant.net/", "Tool");

    private Tool_ToolPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Tool_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Tool_Service ss = new Tool_Service(wsdlURL, SERVICE_NAME);
        Tool port = ss.getToolPort();  
        
        {
        System.out.println("Invoking addReservation...");
        java.lang.String _addReservation_resID = "";
        java.util.List<net.geant.autobahn.intradomain.common.GenericLink> _addReservation_links = null;
        net.geant.autobahn.reservation.ReservationParams _addReservation_params = null;
        try {
            port.addReservation(_addReservation_resID, _addReservation_links, _addReservation_params);

        } catch (ResourceNotFoundException_Exception e) { 
            System.out.println("Expected exception: ResourceNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (RequestException_Exception e) { 
            System.out.println("Expected exception: RequestException has occurred.");
            System.out.println(e.toString());
        } catch (AAIException_Exception e) { 
            System.out.println("Expected exception: AAIException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException_Exception e) { 
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking removeReservation...");
        java.lang.String _removeReservation_resID = "";
        java.util.List<net.geant.autobahn.intradomain.common.GenericLink> _removeReservation_links = null;
        net.geant.autobahn.reservation.ReservationParams _removeReservation_params = null;
        try {
            port.removeReservation(_removeReservation_resID, _removeReservation_links, _removeReservation_params);

        } catch (ReservationNotFoundException_Exception e) { 
            System.out.println("Expected exception: ReservationNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (RequestException_Exception e) { 
            System.out.println("Expected exception: RequestException has occurred.");
            System.out.println(e.toString());
        } catch (AAIException_Exception e) { 
            System.out.println("Expected exception: AAIException has occurred.");
            System.out.println(e.toString());
        } catch (SystemException_Exception e) { 
            System.out.println("Expected exception: SystemException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
