
package net.geant2.jra3.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 20:16:00 EET 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ResourceNotFoundException", targetNamespace = "http://tool.jra3.geant2.net/")
public class ResourceNotFoundException_Exception extends Exception {
    public static final long serialVersionUID = 20110221201600L;
    
    private net.geant2.jra3.tool.ResourceNotFoundException resourceNotFoundException;

    public ResourceNotFoundException_Exception() {
        super();
    }
    
    public ResourceNotFoundException_Exception(String message) {
        super(message);
    }
    
    public ResourceNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotFoundException_Exception(String message, net.geant2.jra3.tool.ResourceNotFoundException resourceNotFoundException) {
        super(message);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public ResourceNotFoundException_Exception(String message, net.geant2.jra3.tool.ResourceNotFoundException resourceNotFoundException, Throwable cause) {
        super(message, cause);
        this.resourceNotFoundException = resourceNotFoundException;
    }

    public net.geant2.jra3.tool.ResourceNotFoundException getFaultInfo() {
        return this.resourceNotFoundException;
    }
}
