
/*
 * 
 */

package net.geant2.jra3.tool;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 20:16:00 EET 2011
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "ToolService", 
                  wsdlLocation = "file:wsdl/heanet.wsdl",
                  targetNamespace = "http://tool.jra3.geant2.net/") 
public class ToolService {

    public final static QName SERVICE = new QName("http://tool.jra3.geant2.net/", "ToolService");
    public final static QName ToolPort = new QName("http://tool.jra3.geant2.net/", "ToolPort");
    private Service service;

    public ToolService(String endPoint) {
        service = Service.create(SERVICE);
        service.addPort(ToolPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }

    /**
     * 
     * @return
     *     returns ToolPort
     */
    @WebEndpoint(name = "ToolPort")
    public Tool getToolPort() {
        Tool port = service.getPort(Tool.class);
        return  port;
    }

}
