
package net.geant2.jra3.tool;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:26:54 EET 2011
 * Generated source version: 2.2.9
 * 
 */
 
public class Tool_ToolPort_Server{

    protected Tool_ToolPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ToolImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Tool_ToolPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
