package net.geant2.jra3.tool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:26:54 EET 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://tool.jra3.geant2.net/", name = "Tool")
@XmlSeeAlso({net.geant2.jra3.constraints.ObjectFactory.class, net.geant2.jra3.intradomain.common.ObjectFactory.class, net.geant2.jra3.reservation.ObjectFactory.class, ObjectFactory.class})
public interface Tool {

    @RequestWrapper(localName = "removeReservation", targetNamespace = "http://tool.jra3.geant2.net/", className = "net.geant2.jra3.tool.RemoveReservation")
    @WebMethod
    @ResponseWrapper(localName = "removeReservationResponse", targetNamespace = "http://tool.jra3.geant2.net/", className = "net.geant2.jra3.tool.RemoveReservationResponse")
    public void removeReservation(
        @WebParam(name = "resID", targetNamespace = "http://tool.jra3.geant2.net/")
        java.lang.String resID,
        @WebParam(name = "links", targetNamespace = "http://tool.jra3.geant2.net/")
        java.util.List<net.geant2.jra3.intradomain.common.GenericLink> links,
        @WebParam(name = "params", targetNamespace = "http://tool.jra3.geant2.net/")
        net.geant2.jra3.reservation.ReservationParams params
    ) throws RequestException_Exception, SystemException_Exception, ReservationNotFoundException_Exception, AAIException_Exception;

    @RequestWrapper(localName = "addReservation", targetNamespace = "http://tool.jra3.geant2.net/", className = "net.geant2.jra3.tool.AddReservation")
    @WebMethod
    @ResponseWrapper(localName = "addReservationResponse", targetNamespace = "http://tool.jra3.geant2.net/", className = "net.geant2.jra3.tool.AddReservationResponse")
    public void addReservation(
        @WebParam(name = "resID", targetNamespace = "http://tool.jra3.geant2.net/")
        java.lang.String resID,
        @WebParam(name = "links", targetNamespace = "http://tool.jra3.geant2.net/")
        java.util.List<net.geant2.jra3.intradomain.common.GenericLink> links,
        @WebParam(name = "params", targetNamespace = "http://tool.jra3.geant2.net/")
        net.geant2.jra3.reservation.ReservationParams params
    ) throws RequestException_Exception, SystemException_Exception, ResourceNotFoundException_Exception, AAIException_Exception;
}
