
package net.geant.autobahn.useraccesspoint.callback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import net.geant.autobahn.useraccesspoint.callback.UapCallback;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Mon Aug 25 16:57:28 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "UapCallbackService", targetNamespace = "http://callback.useraccesspoint.autobahn.geant.net/", wsdlLocation = "file:wsdl/uap-callback.wsdl")
public class UapCallbackService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://callback.useraccesspoint.autobahn.geant.net/", "UapCallbackService");
    private final static QName UapCallbackPort = new QName("http://callback.useraccesspoint.autobahn.geant.net/", "UapCallbackPort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/uap-callback.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:wsdl/uap-callback.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UapCallbackService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UapCallbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UapCallbackService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns UapCallbackPort
     */
    @WebEndpoint(name = "UapCallbackPort")
    public UapCallback getUapCallbackPort() {
        return (UapCallback)super.getPort(UapCallbackPort, UapCallback.class);
    }

}
