
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.geant.autobahn.idcp.notify;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Jul 19 11:08:25 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "OSCARSNotify",
                      portName = "OSCARSNotify",
                      targetNamespace = "http://oscars.es.net/OSCARS",
                      wsdlLocation = "file:src/main/resources/wsdl/IDCP/OSCARS-Notify.wsdl",
                      endpointInterface = "net.geant.autobahn.idcp.notify.OSCARSNotify")
                      
public class OSCARSNotifyImpl implements OSCARSNotify {

    private static final Logger LOG = Logger.getLogger(OSCARSNotifyImpl.class.getName());

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#subscribe(org.oasis_open.docs.wsn.b_2.Subscribe  subscribeRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.SubscribeResponse subscribe(org.oasis_open.docs.wsn.b_2.Subscribe subscribeRequest) throws InvalidMessageContentExpressionFault , UnsupportedPolicyRequestFault , InvalidProducerPropertiesExpressionFault , UnacceptableInitialTerminationTimeFault , UnrecognizedPolicyRequestFault , ResourceUnknownFault , TopicNotSupportedFault , NotifyMessageNotSupportedFault , InvalidFilterFault , TopicExpressionDialectUnknownFault , AAAFaultMessage , InvalidTopicExpressionFault , SubscribeCreationFailedFault    { 
        LOG.info("Executing operation subscribe");
        System.out.println(subscribeRequest);
        try {
            org.oasis_open.docs.wsn.b_2.SubscribeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidMessageContentExpressionFault("InvalidMessageContentExpressionFault...");
        //throw new UnsupportedPolicyRequestFault("UnsupportedPolicyRequestFault...");
        //throw new InvalidProducerPropertiesExpressionFault("InvalidProducerPropertiesExpressionFault...");
        //throw new UnacceptableInitialTerminationTimeFault("UnacceptableInitialTerminationTimeFault...");
        //throw new UnrecognizedPolicyRequestFault("UnrecognizedPolicyRequestFault...");
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new TopicNotSupportedFault("TopicNotSupportedFault...");
        //throw new NotifyMessageNotSupportedFault("NotifyMessageNotSupportedFault...");
        //throw new InvalidFilterFault("InvalidFilterFault...");
        //throw new TopicExpressionDialectUnknownFault("TopicExpressionDialectUnknownFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
        //throw new InvalidTopicExpressionFault("InvalidTopicExpressionFault...");
        //throw new SubscribeCreationFailedFault("SubscribeCreationFailedFault...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#resumeSubscription(org.oasis_open.docs.wsn.b_2.ResumeSubscription  resumeSubscriptionRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.ResumeSubscriptionResponse resumeSubscription(org.oasis_open.docs.wsn.b_2.ResumeSubscription resumeSubscriptionRequest) throws ResourceUnknownFault , ResumeFailedFault , AAAFaultMessage    { 
        LOG.info("Executing operation resumeSubscription");
        System.out.println(resumeSubscriptionRequest);
        try {
            org.oasis_open.docs.wsn.b_2.ResumeSubscriptionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new ResumeFailedFault("ResumeFailedFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#registerPublisher(org.oasis_open.docs.wsn.br_2.RegisterPublisher  registerPublisherRequest )*
     */
    public org.oasis_open.docs.wsn.br_2.RegisterPublisherResponse registerPublisher(org.oasis_open.docs.wsn.br_2.RegisterPublisher registerPublisherRequest) throws PublisherRegistrationRejectedFault , UnacceptableInitialTerminationTimeFault , ResourceUnknownFault , PublisherRegistrationFailedFault , TopicNotSupportedFault , InvalidTopicExpressionFault    { 
        LOG.info("Executing operation registerPublisher");
        System.out.println(registerPublisherRequest);
        try {
            org.oasis_open.docs.wsn.br_2.RegisterPublisherResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PublisherRegistrationRejectedFault("PublisherRegistrationRejectedFault...");
        //throw new UnacceptableInitialTerminationTimeFault("UnacceptableInitialTerminationTimeFault...");
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new PublisherRegistrationFailedFault("PublisherRegistrationFailedFault...");
        //throw new TopicNotSupportedFault("TopicNotSupportedFault...");
        //throw new InvalidTopicExpressionFault("InvalidTopicExpressionFault...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#unsubscribe(org.oasis_open.docs.wsn.b_2.Unsubscribe  unsubscribeRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.UnsubscribeResponse unsubscribe(org.oasis_open.docs.wsn.b_2.Unsubscribe unsubscribeRequest) throws UnableToDestroySubscriptionFault , ResourceUnknownFault , AAAFaultMessage    { 
        LOG.info("Executing operation unsubscribe");
        System.out.println(unsubscribeRequest);
        try {
            org.oasis_open.docs.wsn.b_2.UnsubscribeResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnableToDestroySubscriptionFault("UnableToDestroySubscriptionFault...");
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#pauseSubscription(org.oasis_open.docs.wsn.b_2.PauseSubscription  pauseSubscriptionRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.PauseSubscriptionResponse pauseSubscription(org.oasis_open.docs.wsn.b_2.PauseSubscription pauseSubscriptionRequest) throws PauseFailedFault , ResourceUnknownFault , AAAFaultMessage    { 
        LOG.info("Executing operation pauseSubscription");
        System.out.println(pauseSubscriptionRequest);
        try {
            org.oasis_open.docs.wsn.b_2.PauseSubscriptionResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PauseFailedFault("PauseFailedFault...");
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#renew(org.oasis_open.docs.wsn.b_2.Renew  renewRequest )*
     */
    public org.oasis_open.docs.wsn.b_2.RenewResponse renew(org.oasis_open.docs.wsn.b_2.Renew renewRequest) throws ResourceUnknownFault , UnacceptableTerminationTimeFault , AAAFaultMessage    { 
        LOG.info("Executing operation renew");
        System.out.println(renewRequest);
        try {
            org.oasis_open.docs.wsn.b_2.RenewResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new UnacceptableTerminationTimeFault("UnacceptableTerminationTimeFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#notify(org.oasis_open.docs.wsn.b_2.Notify  notify )*
     */
    public void notify(org.oasis_open.docs.wsn.b_2.Notify notify) { 
        LOG.info("Executing operation notify");
        System.out.println(notify);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.geant.autobahn.idcp.notify.OSCARSNotify#destroyRegistration(org.oasis_open.docs.wsn.br_2.DestroyRegistration  destroyRegistrationRequest )*
     */
    public org.oasis_open.docs.wsn.br_2.DestroyRegistrationResponse destroyRegistration(org.oasis_open.docs.wsn.br_2.DestroyRegistration destroyRegistrationRequest) throws ResourceUnknownFault , ResourceNotDestroyedFault , AAAFaultMessage    { 
        LOG.info("Executing operation destroyRegistration");
        System.out.println(destroyRegistrationRequest);
        try {
            org.oasis_open.docs.wsn.br_2.DestroyRegistrationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new ResourceNotDestroyedFault("ResourceNotDestroyedFault...");
        //throw new AAAFaultMessage("AAAFaultMessage...");
    }

}
