package net.geant.autobahn.idcp.notify;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Sep 10 08:55:56 CEST 2010
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://oscars.es.net/OSCARS", name = "OSCARSNotify")
@XmlSeeAlso({org.ogf.schema.network.topology.ctrlplane._20080828.ObjectFactory.class,org.oasis_open.docs.wsn.br_2.ObjectFactory.class,org.oasis_open.docs.wsrf.r_2.ObjectFactory.class,org.oasis_open.docs.wsn.b_2.ObjectFactory.class,org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class,ObjectFactory.class,org.apache.cxf.ws.addressing.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OSCARSNotify {

    @WebResult(name = "SubscribeResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "SubscribeResponse")
    @WebMethod(operationName = "Subscribe", action = "http://oscars.es.net/OSCARS/Subscribe")
    public org.oasis_open.docs.wsn.b_2.SubscribeResponse subscribe(
        @WebParam(partName = "SubscribeRequest", name = "Subscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Subscribe subscribeRequest
    ) throws InvalidMessageContentExpressionFault, UnsupportedPolicyRequestFault, InvalidProducerPropertiesExpressionFault, UnacceptableInitialTerminationTimeFault, UnrecognizedPolicyRequestFault, ResourceUnknownFault, TopicNotSupportedFault, NotifyMessageNotSupportedFault, InvalidFilterFault, TopicExpressionDialectUnknownFault, AAAFaultMessage, InvalidTopicExpressionFault, SubscribeCreationFailedFault;

    @WebResult(name = "ResumeSubscriptionResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "ResumeSubscriptionResponse")
    @WebMethod(operationName = "ResumeSubscription", action = "http://oscars.es.net/OSCARS/ResumeSubscription")
    public org.oasis_open.docs.wsn.b_2.ResumeSubscriptionResponse resumeSubscription(
        @WebParam(partName = "ResumeSubscriptionRequest", name = "ResumeSubscription", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.ResumeSubscription resumeSubscriptionRequest
    ) throws ResourceUnknownFault, ResumeFailedFault, AAAFaultMessage;

    @WebResult(name = "RegisterPublisherResponse", targetNamespace = "http://docs.oasis-open.org/wsn/br-2", partName = "RegisterPublisherResponse")
    @WebMethod(operationName = "RegisterPublisher", action = "http://oscars.es.net/OSCARS/RegisterPublisher")
    public org.oasis_open.docs.wsn.br_2.RegisterPublisherResponse registerPublisher(
        @WebParam(partName = "RegisterPublisherRequest", name = "RegisterPublisher", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
        org.oasis_open.docs.wsn.br_2.RegisterPublisher registerPublisherRequest
    ) throws PublisherRegistrationRejectedFault, UnacceptableInitialTerminationTimeFault, ResourceUnknownFault, PublisherRegistrationFailedFault, TopicNotSupportedFault, InvalidTopicExpressionFault;

    @WebResult(name = "UnsubscribeResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "UnsubscribeResponse")
    @WebMethod(operationName = "Unsubscribe", action = "http://oscars.es.net/OSCARS/Unsubscribe")
    public org.oasis_open.docs.wsn.b_2.UnsubscribeResponse unsubscribe(
        @WebParam(partName = "UnsubscribeRequest", name = "Unsubscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Unsubscribe unsubscribeRequest
    ) throws UnableToDestroySubscriptionFault, ResourceUnknownFault, AAAFaultMessage;

    @WebResult(name = "PauseSubscriptionResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "PauseSubscriptionResponse")
    @WebMethod(operationName = "PauseSubscription", action = "http://oscars.es.net/OSCARS/PauseSubscription")
    public org.oasis_open.docs.wsn.b_2.PauseSubscriptionResponse pauseSubscription(
        @WebParam(partName = "PauseSubscriptionRequest", name = "PauseSubscription", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.PauseSubscription pauseSubscriptionRequest
    ) throws PauseFailedFault, ResourceUnknownFault, AAAFaultMessage;

    @WebResult(name = "RenewResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "RenewResponse")
    @WebMethod(operationName = "Renew", action = "http://oscars.es.net/OSCARS/Renew")
    public org.oasis_open.docs.wsn.b_2.RenewResponse renew(
        @WebParam(partName = "RenewRequest", name = "Renew", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Renew renewRequest
    ) throws ResourceUnknownFault, UnacceptableTerminationTimeFault, AAAFaultMessage;

    @Oneway
    @WebMethod(operationName = "Notify", action = "http://oscars.es.net/OSCARS/Notify")
    public void notify(
        @WebParam(partName = "Notify", name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Notify notify
    );

    @WebResult(name = "DestroyRegistrationResponse", targetNamespace = "http://docs.oasis-open.org/wsn/br-2", partName = "DestroyRegistrationResponse")
    @WebMethod(operationName = "DestroyRegistration", action = "http://oscars.es.net/OSCARS/DestroyRegistration")
    public org.oasis_open.docs.wsn.br_2.DestroyRegistrationResponse destroyRegistration(
        @WebParam(partName = "DestroyRegistrationRequest", name = "DestroyRegistration", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
        org.oasis_open.docs.wsn.br_2.DestroyRegistration destroyRegistrationRequest
    ) throws ResourceUnknownFault, ResourceNotDestroyedFault, AAAFaultMessage;
}
