
package net.geant.autobahn.idcp.notify;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Jul 19 11:08:24 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

public final class OSCARSNotify_OSCARSNotify_Client {

    private static final QName SERVICE_NAME = new QName("http://oscars.es.net/OSCARS", "OSCARSNotify");

    private OSCARSNotify_OSCARSNotify_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = OSCARSNotify_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OSCARSNotify_Service ss = new OSCARSNotify_Service(wsdlURL, SERVICE_NAME);
        OSCARSNotify port = ss.getOSCARSNotify();  
        
        {
        System.out.println("Invoking subscribe...");
        org.oasis_open.docs.wsn.b_2.Subscribe _subscribe_subscribeRequest = null;
        try {
            org.oasis_open.docs.wsn.b_2.SubscribeResponse _subscribe__return = port.subscribe(_subscribe_subscribeRequest);
            System.out.println("subscribe.result=" + _subscribe__return);

        } catch (InvalidMessageContentExpressionFault e) { 
            System.out.println("Expected exception: InvalidMessageContentExpressionFault has occurred.");
            System.out.println(e.toString());
        } catch (UnsupportedPolicyRequestFault e) { 
            System.out.println("Expected exception: UnsupportedPolicyRequestFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidProducerPropertiesExpressionFault e) { 
            System.out.println("Expected exception: InvalidProducerPropertiesExpressionFault has occurred.");
            System.out.println(e.toString());
        } catch (UnacceptableInitialTerminationTimeFault e) { 
            System.out.println("Expected exception: UnacceptableInitialTerminationTimeFault has occurred.");
            System.out.println(e.toString());
        } catch (UnrecognizedPolicyRequestFault e) { 
            System.out.println("Expected exception: UnrecognizedPolicyRequestFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (TopicNotSupportedFault e) { 
            System.out.println("Expected exception: TopicNotSupportedFault has occurred.");
            System.out.println(e.toString());
        } catch (NotifyMessageNotSupportedFault e) { 
            System.out.println("Expected exception: NotifyMessageNotSupportedFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidFilterFault e) { 
            System.out.println("Expected exception: InvalidFilterFault has occurred.");
            System.out.println(e.toString());
        } catch (TopicExpressionDialectUnknownFault e) { 
            System.out.println("Expected exception: TopicExpressionDialectUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (InvalidTopicExpressionFault e) { 
            System.out.println("Expected exception: InvalidTopicExpressionFault has occurred.");
            System.out.println(e.toString());
        } catch (SubscribeCreationFailedFault e) { 
            System.out.println("Expected exception: SubscribeCreationFailedFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking resumeSubscription...");
        org.oasis_open.docs.wsn.b_2.ResumeSubscription _resumeSubscription_resumeSubscriptionRequest = null;
        try {
            org.oasis_open.docs.wsn.b_2.ResumeSubscriptionResponse _resumeSubscription__return = port.resumeSubscription(_resumeSubscription_resumeSubscriptionRequest);
            System.out.println("resumeSubscription.result=" + _resumeSubscription__return);

        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (ResumeFailedFault e) { 
            System.out.println("Expected exception: ResumeFailedFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking registerPublisher...");
        org.oasis_open.docs.wsn.br_2.RegisterPublisher _registerPublisher_registerPublisherRequest = null;
        try {
            org.oasis_open.docs.wsn.br_2.RegisterPublisherResponse _registerPublisher__return = port.registerPublisher(_registerPublisher_registerPublisherRequest);
            System.out.println("registerPublisher.result=" + _registerPublisher__return);

        } catch (PublisherRegistrationRejectedFault e) { 
            System.out.println("Expected exception: PublisherRegistrationRejectedFault has occurred.");
            System.out.println(e.toString());
        } catch (UnacceptableInitialTerminationTimeFault e) { 
            System.out.println("Expected exception: UnacceptableInitialTerminationTimeFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (PublisherRegistrationFailedFault e) { 
            System.out.println("Expected exception: PublisherRegistrationFailedFault has occurred.");
            System.out.println(e.toString());
        } catch (TopicNotSupportedFault e) { 
            System.out.println("Expected exception: TopicNotSupportedFault has occurred.");
            System.out.println(e.toString());
        } catch (InvalidTopicExpressionFault e) { 
            System.out.println("Expected exception: InvalidTopicExpressionFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unsubscribe...");
        org.oasis_open.docs.wsn.b_2.Unsubscribe _unsubscribe_unsubscribeRequest = null;
        try {
            org.oasis_open.docs.wsn.b_2.UnsubscribeResponse _unsubscribe__return = port.unsubscribe(_unsubscribe_unsubscribeRequest);
            System.out.println("unsubscribe.result=" + _unsubscribe__return);

        } catch (UnableToDestroySubscriptionFault e) { 
            System.out.println("Expected exception: UnableToDestroySubscriptionFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking pauseSubscription...");
        org.oasis_open.docs.wsn.b_2.PauseSubscription _pauseSubscription_pauseSubscriptionRequest = null;
        try {
            org.oasis_open.docs.wsn.b_2.PauseSubscriptionResponse _pauseSubscription__return = port.pauseSubscription(_pauseSubscription_pauseSubscriptionRequest);
            System.out.println("pauseSubscription.result=" + _pauseSubscription__return);

        } catch (PauseFailedFault e) { 
            System.out.println("Expected exception: PauseFailedFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking renew...");
        org.oasis_open.docs.wsn.b_2.Renew _renew_renewRequest = null;
        try {
            org.oasis_open.docs.wsn.b_2.RenewResponse _renew__return = port.renew(_renew_renewRequest);
            System.out.println("renew.result=" + _renew__return);

        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (UnacceptableTerminationTimeFault e) { 
            System.out.println("Expected exception: UnacceptableTerminationTimeFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking notify...");
        org.oasis_open.docs.wsn.b_2.Notify _notify_notify = null;
        port.notify(_notify_notify);


        }
        {
        System.out.println("Invoking destroyRegistration...");
        org.oasis_open.docs.wsn.br_2.DestroyRegistration _destroyRegistration_destroyRegistrationRequest = null;
        try {
            org.oasis_open.docs.wsn.br_2.DestroyRegistrationResponse _destroyRegistration__return = port.destroyRegistration(_destroyRegistration_destroyRegistrationRequest);
            System.out.println("destroyRegistration.result=" + _destroyRegistration__return);

        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceNotDestroyedFault e) { 
            System.out.println("Expected exception: ResourceNotDestroyedFault has occurred.");
            System.out.println(e.toString());
        } catch (AAAFaultMessage e) { 
            System.out.println("Expected exception: AAAFaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
