
package net.geant.autobahn.idcp.notify;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Sep 10 08:55:55 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "ResourceNotDestroyedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class ResourceNotDestroyedFault extends Exception {
    public static final long serialVersionUID = 20100910085555L;
    
    private org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault;

    public ResourceNotDestroyedFault() {
        super();
    }
    
    public ResourceNotDestroyedFault(String message) {
        super(message);
    }
    
    public ResourceNotDestroyedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault) {
        super(message);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault, Throwable cause) {
        super(message, cause);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType getFaultInfo() {
        return this.resourceNotDestroyedFault;
    }
}
