
package net.geant.autobahn.idcp.notify;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Sep 10 08:55:55 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "UnrecognizedPolicyRequestFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnrecognizedPolicyRequestFault extends Exception {
    public static final long serialVersionUID = 20100910085555L;
    
    private org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType unrecognizedPolicyRequestFault;

    public UnrecognizedPolicyRequestFault() {
        super();
    }
    
    public UnrecognizedPolicyRequestFault(String message) {
        super(message);
    }
    
    public UnrecognizedPolicyRequestFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnrecognizedPolicyRequestFault(String message, org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType unrecognizedPolicyRequestFault) {
        super(message);
        this.unrecognizedPolicyRequestFault = unrecognizedPolicyRequestFault;
    }

    public UnrecognizedPolicyRequestFault(String message, org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType unrecognizedPolicyRequestFault, Throwable cause) {
        super(message, cause);
        this.unrecognizedPolicyRequestFault = unrecognizedPolicyRequestFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnrecognizedPolicyRequestFaultType getFaultInfo() {
        return this.unrecognizedPolicyRequestFault;
    }
}
