
package net.geant2.jra3.administration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Mon Mar 02 15:38:46 CET 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://administration.jra3.geant2.net/", name = "Administration")

public interface Administration {

    @WebResult(name = "links", targetNamespace = "")
    @RequestWrapper(localName = "getTopology", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetTopology")
    @ResponseWrapper(localName = "getTopologyResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetTopologyResponse")
    @WebMethod
    public java.util.List<net.geant2.jra3.network.Link> getTopology();

    @RequestWrapper(localName = "setProperties", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.SetProperties")
    @ResponseWrapper(localName = "setPropertiesResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.SetPropertiesResponse")
    @WebMethod
    public void setProperties(
        @WebParam(name = "properties", targetNamespace = "")
        java.util.List<net.geant2.jra3.administration.KeyValue> properties
    );

    @WebResult(name = "serivces", targetNamespace = "")
    @RequestWrapper(localName = "getServices", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetServices")
    @ResponseWrapper(localName = "getServicesResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetServicesResponse")
    @WebMethod
    public java.util.List<net.geant2.jra3.reservation.Service> getServices();

    @WebResult(name = "Properties", targetNamespace = "")
    @RequestWrapper(localName = "getProperties", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetProperties")
    @ResponseWrapper(localName = "getPropertiesResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetPropertiesResponse")
    @WebMethod
    public java.util.List<net.geant2.jra3.administration.KeyValue> getProperties();

    @RequestWrapper(localName = "cancelAllServices", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.CancelAllServices")
    @ResponseWrapper(localName = "cancelAllServicesResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.CancelAllServicesResponse")
    @WebMethod
    public void cancelAllServices();

    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetStatusResponse")
    @WebMethod
    public net.geant2.jra3.administration.Status getStatus();

    @WebResult(name = "service", targetNamespace = "")
    @RequestWrapper(localName = "getService", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetService")
    @ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetServiceResponse")
    @WebMethod
    public net.geant2.jra3.reservation.Service getService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "log", targetNamespace = "")
    @RequestWrapper(localName = "getLog", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetLog")
    @ResponseWrapper(localName = "getLogResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetLogResponse")
    @WebMethod
    public java.lang.String getLog(
        @WebParam(name = "all", targetNamespace = "")
        boolean all
    );

    @WebResult(name = "Reservation", targetNamespace = "")
    @RequestWrapper(localName = "getReservation", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetReservation")
    @ResponseWrapper(localName = "getReservationResponse", targetNamespace = "http://administration.jra3.geant2.net/", className = "net.geant2.jra3.administration.GetReservationResponse")
    @WebMethod
    public net.geant2.jra3.reservation.Reservation getReservation(
        @WebParam(name = "resID", targetNamespace = "")
        java.lang.String resID
    );
}
