
package net.geant2.jra3.administration;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

import net.geant2.jra3.administration.Administration;
import net.geant.edugain.WSSecurity;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Apr 25 14:21:46 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "AdministrationService", targetNamespace = "http://administration.jra3.geant2.net/", wsdlLocation = "file:wsdl/administration.wsdl")
public class AdministrationService {

	private final static QName SERVICE = new QName("http://administration.jra3.geant2.net/", "AdministrationService");
    private final static QName AdministrationPort = new QName("http://administration.jra3.geant2.net/", "AdministrationPort");
    private Service service;
    
    public AdministrationService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(AdministrationPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }
    
    /**
     * 
     * @return
     *     returns Idm2DmPort
     */
    @WebEndpoint(name = "AdministrationPort")
    public Administration getAdministrationPort() {
        
    	Administration port = service.getPort(Administration.class);
    	
    	WSSecurity.setClientTimeout(port);
    	
		try {
			WSSecurity.configureEndpoint(port);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Throwable e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return port;
    }

}
