
package net.geant.autobahn.useraccesspoint.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:31 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://useraccesspoint.autobahn.geant.net/", name = "submitService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://useraccesspoint.autobahn.geant.net/", name = "submitService")

public class SubmitService {

@XmlElement(namespace = "", name = "request")
    private net.geant.autobahn.useraccesspoint.ServiceRequest request;

    public net.geant.autobahn.useraccesspoint.ServiceRequest getRequest ()     {
	           return this.request;
        }

    public void setRequest (   net.geant.autobahn.useraccesspoint.ServiceRequest newRequest  )     {
	           this.request = newRequest;
        }

}

