
package net.geant.autobahn.useraccesspoint.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 11 14:47:31 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://useraccesspoint.autobahn.geant.net/", name = "submitServiceResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://useraccesspoint.autobahn.geant.net/", name = "submitServiceResponse")

public class SubmitServiceResponse {

@XmlElement(namespace = "", name = "serviceID")
    private java.lang.String serviceID;

    public java.lang.String getServiceID ()     {
	           return this.serviceID;
        }

    public void setServiceID (   java.lang.String newServiceID  )     {
	           this.serviceID = newServiceID;
        }

}

