
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-08-30T10:58:32.430+02:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "AAAFault", targetNamespace = "http://oscars.es.net/OSCARS")
public class AAAFaultMessage extends Exception {
    
    private net.geant.autobahn.idcp.AAAFault aaaFault;

    public AAAFaultMessage() {
        super();
    }
    
    public AAAFaultMessage(String message) {
        super(message);
    }
    
    public AAAFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public AAAFaultMessage(String message, net.geant.autobahn.idcp.AAAFault aaaFault) {
        super(message);
        this.aaaFault = aaaFault;
    }

    public AAAFaultMessage(String message, net.geant.autobahn.idcp.AAAFault aaaFault, Throwable cause) {
        super(message, cause);
        this.aaaFault = aaaFault;
    }

    public net.geant.autobahn.idcp.AAAFault getFaultInfo() {
        return this.aaaFault;
    }
}
