
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 16 16:33:14 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "BSSFault", targetNamespace = "http://oscars.es.net/OSCARS")
public class BSSFaultMessage extends Exception {
    public static final long serialVersionUID = 20100716163314L;
    
    private net.geant.autobahn.idcp.BSSFault bssFault;

    public BSSFaultMessage() {
        super();
    }
    
    public BSSFaultMessage(String message) {
        super(message);
    }
    
    public BSSFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public BSSFaultMessage(String message, net.geant.autobahn.idcp.BSSFault bssFault) {
        super(message);
        this.bssFault = bssFault;
    }

    public BSSFaultMessage(String message, net.geant.autobahn.idcp.BSSFault bssFault, Throwable cause) {
        super(message, cause);
        this.bssFault = bssFault;
    }

    public net.geant.autobahn.idcp.BSSFault getFaultInfo() {
        return this.bssFault;
    }
}
