
package net.geant.autobahn.idcp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 16 16:39:41 CEST 2010
 * Generated source version: 2.2.6
 * 
 */
 
public class OSCARSNotify_OSCARSNotify_Server{

    protected OSCARSNotify_OSCARSNotify_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new OSCARSNotifyImpl();
        String address = "http://oscars.es.net/axis2/services/OSCARSNotify";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new OSCARSNotify_OSCARSNotify_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
