package net.geant.autobahn.idcp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 16 16:33:14 CEST 2010
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://oscars.es.net/OSCARS", name = "OSCARS")
@XmlSeeAlso({org.ogf.schema.network.topology.ctrlplane._20080828.ObjectFactory.class,ObjectFactory.class,org.oasis_open.docs.wsn.b_2.ObjectFactory.class,org.oasis_open.docs.wsrf.r_2.ObjectFactory.class,org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class})
public interface OSCARS {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cancelReservationResponse", targetNamespace = "http://oscars.es.net/OSCARS", partName = "cancelReservationResponse")
    @WebMethod(action = "http://oscars.es.net/OSCARS/cancelReservation")
    public java.lang.String cancelReservation(
        @WebParam(partName = "cancelReservation", name = "cancelReservation", targetNamespace = "http://oscars.es.net/OSCARS")
        GlobalReservationId cancelReservation
    ) throws AAAFaultMessage, BSSFaultMessage;

    @RequestWrapper(localName = "createReservation", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.ResCreateContent")
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.CreateReply")
    @WebMethod(action = "http://oscars.es.net/OSCARS/createReservation")
    public void createReservation(
        @WebParam(mode = WebParam.Mode.INOUT, name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> globalReservationId,
        @WebParam(name = "startTime", targetNamespace = "http://oscars.es.net/OSCARS")
        long startTime,
        @WebParam(name = "endTime", targetNamespace = "http://oscars.es.net/OSCARS")
        long endTime,
        @WebParam(name = "bandwidth", targetNamespace = "http://oscars.es.net/OSCARS")
        int bandwidth,
        @WebParam(name = "description", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String description,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pathInfo", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<PathInfo> pathInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "token", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> token,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> status
    ) throws AAAFaultMessage, BSSFaultMessage;

    @RequestWrapper(localName = "queryReservation", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.GlobalReservationId")
    @ResponseWrapper(localName = "queryReservationResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.ResDetails")
    @WebMethod(action = "http://oscars.es.net/OSCARS/queryReservation")
    public void queryReservation(
        @WebParam(name = "gri", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String gri,
        @WebParam(mode = WebParam.Mode.OUT, name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> globalReservationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "login", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> login,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "startTime", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.Long> startTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "endTime", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.Long> endTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "createTime", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.Long> createTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "bandwidth", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.Integer> bandwidth,
        @WebParam(mode = WebParam.Mode.OUT, name = "description", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> description,
        @WebParam(mode = WebParam.Mode.OUT, name = "pathInfo", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<PathInfo> pathInfo
    ) throws AAAFaultMessage, BSSFaultMessage;

    @RequestWrapper(localName = "refreshPath", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.RefreshPathContent")
    @ResponseWrapper(localName = "refreshPathResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.RefreshPathResponseContent")
    @WebMethod(action = "http://oscars.es.net/OSCARS/refreshPath")
    public void refreshPath(
        @WebParam(name = "token", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String token,
        @WebParam(mode = WebParam.Mode.INOUT, name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> globalReservationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> status
    ) throws AAAFaultMessage, BSSFaultMessage;

    @RequestWrapper(localName = "teardownPath", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.TeardownPathContent")
    @ResponseWrapper(localName = "teardownPathResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.TeardownPathResponseContent")
    @WebMethod(action = "http://oscars.es.net/OSCARS/teardownPath")
    public void teardownPath(
        @WebParam(name = "token", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String token,
        @WebParam(mode = WebParam.Mode.INOUT, name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> globalReservationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> status
    ) throws AAAFaultMessage, BSSFaultMessage;

    @RequestWrapper(localName = "createPath", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.CreatePathContent")
    @ResponseWrapper(localName = "createPathResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.CreatePathResponseContent")
    @WebMethod(action = "http://oscars.es.net/OSCARS/createPath")
    public void createPath(
        @WebParam(name = "token", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String token,
        @WebParam(mode = WebParam.Mode.INOUT, name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> globalReservationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> status
    ) throws AAAFaultMessage, BSSFaultMessage;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getNetworkTopologyResponse", targetNamespace = "http://oscars.es.net/OSCARS", partName = "getNetworkTopologyResponse")
    @WebMethod(action = "http://oscars.es.net/OSCARS/getNetworkTopology")
    public GetTopologyResponseContent getNetworkTopology(
        @WebParam(partName = "getNetworkTopology", name = "getNetworkTopology", targetNamespace = "http://oscars.es.net/OSCARS")
        GetTopologyContent getNetworkTopology
    ) throws AAAFaultMessage, BSSFaultMessage;

    @WebResult(name = "reservation", targetNamespace = "http://oscars.es.net/OSCARS")
    @RequestWrapper(localName = "modifyReservation", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.ModifyResContent")
    @ResponseWrapper(localName = "modifyReservationResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.ModifyResReply")
    @WebMethod(action = "http://oscars.es.net/OSCARS/modifyReservation")
    public net.geant.autobahn.idcp.ResDetails modifyReservation(
        @WebParam(name = "globalReservationId", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String globalReservationId,
        @WebParam(name = "startTime", targetNamespace = "http://oscars.es.net/OSCARS")
        long startTime,
        @WebParam(name = "endTime", targetNamespace = "http://oscars.es.net/OSCARS")
        long endTime,
        @WebParam(name = "bandwidth", targetNamespace = "http://oscars.es.net/OSCARS")
        int bandwidth,
        @WebParam(name = "description", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String description,
        @WebParam(name = "pathInfo", targetNamespace = "http://oscars.es.net/OSCARS")
        net.geant.autobahn.idcp.PathInfo pathInfo
    ) throws AAAFaultMessage, BSSFaultMessage;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "Notify", action = "http://oscars.es.net/OSCARS/Notify")
    public void notify(
        @WebParam(partName = "Notify", name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Notify notify
    );

    @RequestWrapper(localName = "forward", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.Forward")
    @ResponseWrapper(localName = "forwardResponse", targetNamespace = "http://oscars.es.net/OSCARS", className = "net.geant.autobahn.idcp.ForwardReply")
    @WebMethod(action = "http://oscars.es.net/OSCARS/forward")
    public void forward(
        @WebParam(name = "payload", targetNamespace = "http://oscars.es.net/OSCARS")
        net.geant.autobahn.idcp.ForwardPayload payload,
        @WebParam(name = "payloadSender", targetNamespace = "http://oscars.es.net/OSCARS")
        java.lang.String payloadSender,
        @WebParam(mode = WebParam.Mode.OUT, name = "contentType", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> contentType,
        @WebParam(mode = WebParam.Mode.OUT, name = "createReservation", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<CreateReply> createReservation,
        @WebParam(mode = WebParam.Mode.OUT, name = "modifyReservation", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<ModifyResReply> modifyReservation,
        @WebParam(mode = WebParam.Mode.OUT, name = "cancelReservation", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<java.lang.String> cancelReservation,
        @WebParam(mode = WebParam.Mode.OUT, name = "queryReservation", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<ResDetails> queryReservation,
        @WebParam(mode = WebParam.Mode.OUT, name = "listReservations", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<ListReply> listReservations,
        @WebParam(mode = WebParam.Mode.OUT, name = "createPath", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<CreatePathResponseContent> createPath,
        @WebParam(mode = WebParam.Mode.OUT, name = "refreshPath", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<RefreshPathResponseContent> refreshPath,
        @WebParam(mode = WebParam.Mode.OUT, name = "teardownPath", targetNamespace = "http://oscars.es.net/OSCARS")
        javax.xml.ws.Holder<TeardownPathResponseContent> teardownPath
    ) throws AAAFaultMessage, BSSFaultMessage;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "listReservationsResponse", targetNamespace = "http://oscars.es.net/OSCARS", partName = "listReservationsResponse")
    @WebMethod(action = "http://oscars.es.net/OSCARS/listReservations")
    public ListReply listReservations(
        @WebParam(partName = "listReservations", name = "listReservations", targetNamespace = "http://oscars.es.net/OSCARS")
        ListRequest listReservations
    ) throws AAAFaultMessage, BSSFaultMessage;
}
