package net.geant.autobahn.idcp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-04T15:26:52.958+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://oscars.es.net/OSCARS", name = "OSCARSNotifyOnly")
@XmlSeeAlso({org.ogf.schema.network.topology.ctrlplane._20080828.ObjectFactory.class, ObjectFactory.class, org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, org.oasis_open.docs.wsrf.r_2.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.apache.cxf.ws.addressing.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OSCARSNotifyOnly {

    @Oneway
    @WebMethod(operationName = "Notify", action = "http://oscars.es.net/OSCARS/Notify")
    public void notify(
        @WebParam(partName = "Notify", name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Notify notify
    );
}
