package net.geant.autobahn.idcp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-04T15:26:52.966+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "OSCARSNotifyOnlyService", 
                  wsdlLocation = "file:etc/wsdl/IDCP/OSCARS-NotifyOnly.wsdl",
                  targetNamespace = "http://oscars.es.net/OSCARS") 
public class OSCARSNotifyOnlyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://oscars.es.net/OSCARS", "OSCARSNotifyOnlyService");
    public final static QName OSCARSNotifyOnly = new QName("http://oscars.es.net/OSCARS", "OSCARSNotifyOnly");
    static {
        URL url = null;
        try {
            url = new URL("file:etc/wsdl/IDCP/OSCARS-NotifyOnly.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OSCARSNotifyOnlyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:etc/wsdl/IDCP/OSCARS-NotifyOnly.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OSCARSNotifyOnlyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OSCARSNotifyOnlyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OSCARSNotifyOnlyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OSCARSNotifyOnly
     */
    @WebEndpoint(name = "OSCARSNotifyOnly")
    public OSCARSNotifyOnly getOSCARSNotifyOnly() {
        return super.getPort(OSCARSNotifyOnly, OSCARSNotifyOnly.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OSCARSNotifyOnly
     */
    @WebEndpoint(name = "OSCARSNotifyOnly")
    public OSCARSNotifyOnly getOSCARSNotifyOnly(WebServiceFeature... features) {
        return super.getPort(OSCARSNotifyOnly, OSCARSNotifyOnly.class, features);
    }

}
