
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-08-30T10:58:32.448+02:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "PublisherRegistrationFailedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class PublisherRegistrationFailedFault extends Exception {
    
    private org.oasis_open.docs.wsn.br_2.PublisherRegistrationFailedFaultType publisherRegistrationFailedFault;

    public PublisherRegistrationFailedFault() {
        super();
    }
    
    public PublisherRegistrationFailedFault(String message) {
        super(message);
    }
    
    public PublisherRegistrationFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PublisherRegistrationFailedFault(String message, org.oasis_open.docs.wsn.br_2.PublisherRegistrationFailedFaultType publisherRegistrationFailedFault) {
        super(message);
        this.publisherRegistrationFailedFault = publisherRegistrationFailedFault;
    }

    public PublisherRegistrationFailedFault(String message, org.oasis_open.docs.wsn.br_2.PublisherRegistrationFailedFaultType publisherRegistrationFailedFault, Throwable cause) {
        super(message, cause);
        this.publisherRegistrationFailedFault = publisherRegistrationFailedFault;
    }

    public org.oasis_open.docs.wsn.br_2.PublisherRegistrationFailedFaultType getFaultInfo() {
        return this.publisherRegistrationFailedFault;
    }
}
