
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 16 16:39:41 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "PublisherRegistrationRejectedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class PublisherRegistrationRejectedFault extends Exception {
    public static final long serialVersionUID = 20100716163941L;
    
    private org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType publisherRegistrationRejectedFault;

    public PublisherRegistrationRejectedFault() {
        super();
    }
    
    public PublisherRegistrationRejectedFault(String message) {
        super(message);
    }
    
    public PublisherRegistrationRejectedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PublisherRegistrationRejectedFault(String message, org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType publisherRegistrationRejectedFault) {
        super(message);
        this.publisherRegistrationRejectedFault = publisherRegistrationRejectedFault;
    }

    public PublisherRegistrationRejectedFault(String message, org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType publisherRegistrationRejectedFault, Throwable cause) {
        super(message, cause);
        this.publisherRegistrationRejectedFault = publisherRegistrationRejectedFault;
    }

    public org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType getFaultInfo() {
        return this.publisherRegistrationRejectedFault;
    }
}
