
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-05T13:54:31.302+02:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "ResourceNotDestroyedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class ResourceNotDestroyedFault extends Exception {
    
    private org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault;

    public ResourceNotDestroyedFault() {
        super();
    }
    
    public ResourceNotDestroyedFault(String message) {
        super(message);
    }
    
    public ResourceNotDestroyedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault) {
        super(message);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public ResourceNotDestroyedFault(String message, org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType resourceNotDestroyedFault, Throwable cause) {
        super(message, cause);
        this.resourceNotDestroyedFault = resourceNotDestroyedFault;
    }

    public org.oasis_open.docs.wsn.br_2.ResourceNotDestroyedFaultType getFaultInfo() {
        return this.resourceNotDestroyedFault;
    }
}
