
package net.geant.autobahn.idcp;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Fri Jul 16 16:39:41 CEST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableTerminationTimeFault extends Exception {
    public static final long serialVersionUID = 20100716163941L;
    
    private org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault;

    public UnacceptableTerminationTimeFault() {
        super();
    }
    
    public UnacceptableTerminationTimeFault(String message) {
        super(message);
    }
    
    public UnacceptableTerminationTimeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnacceptableTerminationTimeFault(String message, org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault) {
        super(message);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public UnacceptableTerminationTimeFault(String message, org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault, Throwable cause) {
        super(message, cause);
        this.unacceptableTerminationTimeFault = unacceptableTerminationTimeFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType getFaultInfo() {
        return this.unacceptableTerminationTimeFault;
    }
}
