
package net.geant.autobahn.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:35:15 EET 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "AAIException", targetNamespace = "http://tool.autobahn.geant.net/")
public class AAIException_Exception extends Exception {
    public static final long serialVersionUID = 20110221173515L;
    
    private net.geant.autobahn.tool.AAIException aaiException;

    public AAIException_Exception() {
        super();
    }
    
    public AAIException_Exception(String message) {
        super(message);
    }
    
    public AAIException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AAIException_Exception(String message, net.geant.autobahn.tool.AAIException aaiException) {
        super(message);
        this.aaiException = aaiException;
    }

    public AAIException_Exception(String message, net.geant.autobahn.tool.AAIException aaiException, Throwable cause) {
        super(message, cause);
        this.aaiException = aaiException;
    }

    public net.geant.autobahn.tool.AAIException getFaultInfo() {
        return this.aaiException;
    }
}
