
package net.geant.autobahn.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:35:15 EET 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "ReservationNotFoundException", targetNamespace = "http://tool.autobahn.geant.net/")
public class ReservationNotFoundException_Exception extends Exception {
    public static final long serialVersionUID = 20110221173515L;
    
    private net.geant.autobahn.tool.ReservationNotFoundException reservationNotFoundException;

    public ReservationNotFoundException_Exception() {
        super();
    }
    
    public ReservationNotFoundException_Exception(String message) {
        super(message);
    }
    
    public ReservationNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ReservationNotFoundException_Exception(String message, net.geant.autobahn.tool.ReservationNotFoundException reservationNotFoundException) {
        super(message);
        this.reservationNotFoundException = reservationNotFoundException;
    }

    public ReservationNotFoundException_Exception(String message, net.geant.autobahn.tool.ReservationNotFoundException reservationNotFoundException, Throwable cause) {
        super(message, cause);
        this.reservationNotFoundException = reservationNotFoundException;
    }

    public net.geant.autobahn.tool.ReservationNotFoundException getFaultInfo() {
        return this.reservationNotFoundException;
    }
}
