
package net.geant.autobahn.tool;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:35:15 EET 2011
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "SystemException", targetNamespace = "http://tool.autobahn.geant.net/")
public class SystemException_Exception extends Exception {
    public static final long serialVersionUID = 20110221173515L;
    
    private net.geant.autobahn.tool.SystemException systemException;

    public SystemException_Exception() {
        super();
    }
    
    public SystemException_Exception(String message) {
        super(message);
    }
    
    public SystemException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SystemException_Exception(String message, net.geant.autobahn.tool.SystemException systemException) {
        super(message);
        this.systemException = systemException;
    }

    public SystemException_Exception(String message, net.geant.autobahn.tool.SystemException systemException, Throwable cause) {
        super(message, cause);
        this.systemException = systemException;
    }

    public net.geant.autobahn.tool.SystemException getFaultInfo() {
        return this.systemException;
    }
}
