package net.geant.autobahn.tool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Feb 21 17:35:15 EET 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://tool.autobahn.geant.net/", name = "Tool")
@XmlSeeAlso({net.geant.autobahn.constraints.ObjectFactory.class, ObjectFactory.class, net.geant.autobahn.intradomain.common.ObjectFactory.class, net.geant.autobahn.tool.types.ObjectFactory.class})
public interface Tool {

    @RequestWrapper(localName = "addReservation", targetNamespace = "http://tool.autobahn.geant.net/", className = "net.geant.autobahn.tool.AddReservation")
    @WebMethod
    @ResponseWrapper(localName = "addReservationResponse", targetNamespace = "http://tool.autobahn.geant.net/", className = "net.geant.autobahn.tool.AddReservationResponse")
    public void addReservation(
        @WebParam(name = "resID", targetNamespace = "")
        java.lang.String resID,
        @WebParam(name = "ipath", targetNamespace = "")
        net.geant.autobahn.tool.types.IntradomainPathType ipath,
        @WebParam(name = "params", targetNamespace = "")
        net.geant.autobahn.tool.types.ReservationParamsType params
    ) throws ResourceNotFoundException_Exception, RequestException_Exception, AAIException_Exception, SystemException_Exception;

    @RequestWrapper(localName = "removeReservation", targetNamespace = "http://tool.autobahn.geant.net/", className = "net.geant.autobahn.tool.RemoveReservation")
    @WebMethod
    @ResponseWrapper(localName = "removeReservationResponse", targetNamespace = "http://tool.autobahn.geant.net/", className = "net.geant.autobahn.tool.RemoveReservationResponse")
    public void removeReservation(
        @WebParam(name = "resID", targetNamespace = "")
        java.lang.String resID,
        @WebParam(name = "ipath", targetNamespace = "")
        net.geant.autobahn.tool.types.IntradomainPathType ipath,
        @WebParam(name = "params", targetNamespace = "")
        net.geant.autobahn.tool.types.ReservationParamsType params
    ) throws ReservationNotFoundException_Exception, RequestException_Exception, AAIException_Exception, SystemException_Exception;
}
