
package net.geant.autobahn.dm2idm.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by the CXF 2.0.3-incubator
 * Fri Apr 04 12:14:07 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@XmlRootElement(namespace = "http://dm2idm.autobahn.geant.net/", name = "finishResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "http://dm2idm.autobahn.geant.net/", name = "finishResponse")

public class FinishResponse {


}

