
package net.geant.autobahn.administration;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.soap.SOAPBinding;

import net.geant.autobahn.administration.Administration;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Apr 25 14:17:30 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebServiceClient(name = "AdministrationService", targetNamespace = "http://administration.jra3.geant2.net/", wsdlLocation = "file:wsdl/administration.wsdl")
public class AdministrationService {

    private final static QName SERVICE = new QName("http://administration.jra3.geant2.net/", "AdministrationService");
    private final static QName AdministrationPort = new QName("http://administration.jra3.geant2.net/", "AdministrationPort");
    private Service service;
    
    public AdministrationService(String endPoint) {
    	service = Service.create(SERVICE);
    	service.addPort(AdministrationPort, SOAPBinding.SOAP11HTTP_BINDING, endPoint);
    }

    /**
     * 
     * @return
     *     returns AdministrationPort
     */
    @WebEndpoint(name = "AdministrationPort")
    public Administration getAdministrationPort() {
        return service.getPort(Administration.class);
    }

}
