
package net.geant.autobahn.administration;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Apr 25 14:17:30 CEST 2008
 * Generated source version: 2.0.3-incubator
 * 
 */

public final class Administration_AdministrationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://administration.autobahn.geant.net/", "AdministrationService");
    private static final String pionier = "http://poznan.autobahn.psnc.pl:8080/autobahn/administration";
    
    private Administration_AdministrationPort_Client() {
    }

    public static void main(String args[]) throws Exception {

    	AdministrationService service = new AdministrationService(pionier);
    	Administration port = service.getAdministrationPort();
    	
    	String log = port.getLog(true);
    	
    	System.out.println(log);

        System.exit(0);
    }

}
