
package net.geant2.jra3.proxy;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.3-incubator
 * Fri Jan 08 10:34:45 EET 2010
 * Generated source version: 2.0.3-incubator
 * 
 */

@WebService(targetNamespace = "http://proxy.jra3.geant2.net/", name = "Proxy")

public interface Proxy {

    @RequestWrapper(localName = "createReservation", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.CreateReservation")
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.CreateReservationResponse")
    @WebMethod
    public void createReservation(
        @WebParam(targetNamespace = "", name = "proxyInfo")
        net.geant2.jra3.proxy.ProxyInfo proxyInfo,
        @WebParam(targetNamespace = "", name = "reservation")
        net.geant2.jra3.proxy.ReservationParams reservation
    ) throws ProxyException_Exception;

    @WebResult(targetNamespace = "", name = "reservation")
    @RequestWrapper(localName = "queryReservation", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.QueryReservation")
    @ResponseWrapper(localName = "queryReservationResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.QueryReservationResponse")
    @WebMethod
    public net.geant2.jra3.proxy.Reservation queryReservation(
        @WebParam(targetNamespace = "", name = "resID")
        java.lang.String resID
    ) throws ProxyException_Exception;

    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.CancelReservationResponse")
    @WebMethod
    public void cancelReservation(
        @WebParam(targetNamespace = "", name = "proxyInfo")
        net.geant2.jra3.proxy.ProxyInfo proxyInfo,
        @WebParam(targetNamespace = "", name = "resID")
        java.lang.String resID
    ) throws ProxyException_Exception;

    @WebResult(targetNamespace = "", name = "proxyInfo")
    @RequestWrapper(localName = "getProxyInfo", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.GetProxyInfo")
    @ResponseWrapper(localName = "getProxyInfoResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.GetProxyInfoResponse")
    @WebMethod
    public net.geant2.jra3.proxy.ProxyInfo getProxyInfo();

    @WebResult(targetNamespace = "", name = "links")
    @RequestWrapper(localName = "getTopology", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.GetTopology")
    @ResponseWrapper(localName = "getTopologyResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.GetTopologyResponse")
    @WebMethod
    public java.util.List<net.geant2.jra3.proxy.Link> getTopology(
        @WebParam(targetNamespace = "", name = "proxyInfo")
        net.geant2.jra3.proxy.ProxyInfo proxyInfo
    );

    @WebResult(targetNamespace = "", name = "reservations")
    @RequestWrapper(localName = "listReservations", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.ListReservations")
    @ResponseWrapper(localName = "listReservationsResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.ListReservationsResponse")
    @WebMethod
    public java.util.List<net.geant2.jra3.proxy.Reservation> listReservations();

    @RequestWrapper(localName = "forward", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.Forward")
    @ResponseWrapper(localName = "forwardResponse", targetNamespace = "http://proxy.jra3.geant2.net/", className = "net.geant2.jra3.proxy.ForwardResponse")
    @WebMethod
    public void forward(
        @WebParam(targetNamespace = "", name = "reservation")
        net.geant2.jra3.proxy.Reservation reservation
    ) throws ProxyException_Exception;
}
